'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    ' or if you encounter build errors in this file, go to the Project Designer
    ' (go to Project Properties or double-click the My Project node in
    ' Solution Explorer), and make changes on the Application tab.
    '
    Partial Friend Class MyApplication
        
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Syncfusion.Licensing.SyncfusionLicenseProvider.RegisterLicense("Mgo+DSMBaFt/QHRqVVhjVFpFdEBBXHxAd1p/VWJYdVt5flBPcDwsT3RfQF5jSH5adkFmUHtfcX1VRg==;Mgo+DSMBPh8sVXJ0S0J+XE9HflRDX3xKf0x/TGpQb19xflBPallYVBYiSV9jS31Td0VqWXtbeXBURGFYUQ==;ORg4AjUWIQA/Gnt2VVhkQlFadVdJXGFWfVJpTGpQdk5xdV9DaVZUTWY/P1ZhSXxQdkRjUH9adX1RR2JYUkQ=;OTAxNzQwQDMyMzAyZTM0MmUzMFNGalZ5RUN4Q3NUOERrcFJ4M3JsS1pEVkJUbndGa0JpOG1mMjlpZlZqcUk9;OTAxNzQxQDMyMzAyZTM0MmUzMEE1aE5WN0ZVR3BsVDh6N0tHdkNJWDFCUmg0bG41bzhKTkNRb3l6QTlRMkE9;NRAiBiAaIQQuGjN/V0Z+WE9EaFxKVmJLYVB3WmpQdldgdVRMZVVbQX9PIiBoS35RdUViWXZedHFcQmFfU0x2;OTAxNzQzQDMyMzAyZTM0MmUzMFR2OThWRENJeTF4WTBqbktCY3A3cVVVcjZNWU1WSXBRZEYxLzRFcHBUYmM9;OTAxNzQ0QDMyMzAyZTM0MmUzMHBBdUVySmNpU3ROOEJJWStielBsNWl3ZUNEQndqT1BMTFg5RHZIdVJkaGc9;Mgo+DSMBMAY9C3t2VVhkQlFadVdJXGFWfVJpTGpQdk5xdV9DaVZUTWY/P1ZhSXxQdkRjUH9adX1RR2ReVEQ=;OTAxNzQ2QDMyMzAyZTM0MmUzMEx4eXpkMkxNa0VjVThScW8xL3FnK0FyVXkwWTd3NEQweTMyMXlQclY4a0U9;OTAxNzQ3QDMyMzAyZTM0MmUzMGIrVFFMbENkVEx3SDRicEtDQ1owVFI3NU81c0FCL1ZhZXJMNGdQTVU3Wlk9;OTAxNzQ4QDMyMzAyZTM0MmUzMFR2OThWRENJeTF4WTBqbktCY3A3cVVVcjZNWU1WSXBRZEYxLzRFcHBUYmM9")
            Me.IsSingleInstance = false
            Me.EnableVisualStyles = true
            Me.SaveMySettingsOnExit = true
            Me.ShutDownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterAllFormsClose
        End Sub
        
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Protected Overrides Sub OnCreateMainForm()
            Me.MainForm = Global.Brgy_Daang_Bukid_MIS.Login
        End Sub
    End Class
End Namespace
